# Generated by Django 4.0.5 on 2022-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_coachid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coachId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trenerId',
            field=models.IntegerField(default=1, verbose_name='Выберите сопровождающего Вас тренера'),
            preserve_default=False,
        ),
    ]
