# Generated by Django 4.0.5 on 2022-06-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_trenerid_userprofile_coachid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FederalOkrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coachId',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passwordRepeat',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.coach'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='federalOkrug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.federalokrug'),
        ),
    ]
