# Generated by Django 4.0.5 on 2022-06-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_firstname_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='firstname',
        ),
    ]
