# Generated by Django 4.0.5 on 2022-06-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_coachid_userprofile_trenerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trenerId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coachId',
            field=models.IntegerField(default=1, verbose_name='Id сопровождающего тренера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='classNumber',
            field=models.IntegerField(verbose_name='Класс в котором обучается ученик'),
        ),
    ]
