# Generated by Django 4.0.5 on 2022-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coach_federalokrug_remove_userprofile_coachid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
